### ISSUE TITLE
v1.0 feature checklist

### ISSUE THREAD

**Issue by thecoder876** [SimpleEdit/editor#23]
Checklist:
- [ ] Desktop app (in progress, #21)
- [ ] Core editing system
- [ ] Better UI
- [ ] Files import and export system (.sel file extension)

**Comment by AmpersandGD** [comment]
> Checklist:
> 
> * [ ]  Desktop app (in progress, see #21)
> * [ ]  Core editing system
> * [ ]  Better UI
> * [ ]  Files import and export system (.sel file extension)


Okay what the frick is a .sel file

**Comment by thecoder876** [comment]
> > Checklist:
> > 
> > * [ ]   Desktop app (in progress, see #21)
> > * [ ]   Core editing system
> > * [ ]   Better UI
> > * [ ]   Files import and export system (.sel file extension)
> 
> Okay what the frick is a .sel file

@AmpersandGD New extension that we'll make. SEL = SimpleEdit Level

**Comment by AmpersandGD** [comment]
> > > Checklist:
> > > 
> > > * [ ]    Desktop app (in progress, see #21)
> > > * [ ]    Core editing system
> > > * [ ]    Better UI
> > > * [ ]    Files import and export system (.sel file extension)
> > 
> > 
> > Okay what the frick is a .sel file
> 
> @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level



It should be encrypted like so:
The level data in the pure text is encrypted into the .sel file
Then nothing else, we're done.
But we need to know how to read GD level data.

**Comment by AmpersandGD** [comment]
> > > Checklist:
> > > 
> > > * [ ]    Desktop app (in progress, see #21)
> > > * [ ]    Core editing system
> > > * [ ]    Better UI
> > > * [ ]    Files import and export system (.sel file extension)
> > 
> > 
> > Okay what the frick is a .sel file
> 
> @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level


But unfortunately, the .sel file extension name is taken.
![image](https://user-images.githubusercontent.com/64666021/107407993-3545d980-6abf-11eb-9f3d-97d1a17eef16.png)

**Comment by thecoder876** [comment]
> > > > Checklist:
> > > > 
> > > > * [ ]     Desktop app (in progress, see #21)
> > > > * [ ]     Core editing system
> > > > * [ ]     Better UI
> > > > * [ ]     Files import and export system (.sel file extension)
> > > 
> > > 
> > > Okay what the frick is a .sel file
> > 
> > 
> > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> 
> But unfortunately, the .sel file extension name is taken.
> ![image](https://user-images.githubusercontent.com/64666021/107407993-3545d980-6abf-11eb-9f3d-97d1a17eef16.png)

Umm, maybe ``.eel`` then?

**Comment by thecoder876** [comment]
> > > > > Checklist:
> > > > > 
> > > > > * [ ]      Desktop app (in progress, see #21)
> > > > > * [ ]      Core editing system
> > > > > * [ ]      Better UI
> > > > > * [ ]      Files import and export system (.sel file extension)
> > > > 
> > > > 
> > > > Okay what the frick is a .sel file
> > > 
> > > 
> > > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> > 
> > 
> > But unfortunately, the .sel file extension name is taken.
> > ![image](https://user-images.githubusercontent.com/64666021/107407993-3545d980-6abf-11eb-9f3d-97d1a17eef16.png)
> 
> Umm, maybe `.sl` then?

**Comment by AmpersandGD** [comment]
> > > > > > Checklist:
> > > > > > 
> > > > > > * [ ]       Desktop app (in progress, see #21)
> > > > > > * [ ]       Core editing system
> > > > > > * [ ]       Better UI
> > > > > > * [ ]       Files import and export system (.sel file extension)
> > > > > 
> > > > > 
> > > > > Okay what the frick is a .sel file
> > > > 
> > > > 
> > > > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> > > 
> > > 
> > > But unfortunately, the .sel file extension name is taken.
> > > ![image](https://user-images.githubusercontent.com/64666021/107407993-3545d980-6abf-11eb-9f3d-97d1a17eef16.png)
> > 
> > 
> > Umm, maybe `.sl` then?



![image](https://user-images.githubusercontent.com/64666021/107409719-53143e00-6ac1-11eb-9523-b5fc5ad03e62.png)
Come on

**Comment by thecoder876** [comment]
> > > > > > > Checklist:
> > > > > > > 
> > > > > > > * [ ]        Desktop app (in progress, see #21)
> > > > > > > * [ ]        Core editing system
> > > > > > > * [ ]        Better UI
> > > > > > > * [ ]        Files import and export system (.sel file extension)
> > > > > > 
> > > > > > 
> > > > > > Okay what the frick is a .sel file
> > > > > 
> > > > > 
> > > > > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> > > > 
> > > > 
> > > > But unfortunately, the .sel file extension name is taken.
> > > > ![image](https://user-images.githubusercontent.com/64666021/107407993-3545d980-6abf-11eb-9f3d-97d1a17eef16.png)
> > > 
> > > 
> > > Umm, maybe `.sl` then?
> 
> ![image](https://user-images.githubusercontent.com/64666021/107409719-53143e00-6ac1-11eb-9523-b5fc5ad03e62.png)
> Come on

Whyeeeeee??? @AmpersandGD Then maybe ``.lse``?

**Comment by AmpersandGD** [comment]
> > > > > > > > Checklist:
> > > > > > > > 
> > > > > > > > * [ ]         Desktop app (in progress, see #21)
> > > > > > > > * [ ]         Core editing system
> > > > > > > > * [ ]         Better UI
> > > > > > > > * [ ]         Files import and export system (.sel file extension)
> > > > > > > 
> > > > > > > 
> > > > > > > Okay what the frick is a .sel file
> > > > > > 
> > > > > > 
> > > > > > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> > > > > 
> > > > > 
> > > > > But unfortunately, the .sel file extension name is taken.
> > > > > ~snip
> > > > 
> > > > 
> > > > Umm, maybe `.sl` then?
> > 
> > 
> > ~snip~
> > Come on
> 
> Whyeeeeee??? @AmpersandGD Then maybe `.lse`? Or `.eel`?



Those file names are both taken, but good news, the names `.gdlevel`  and `.selevel` are both available!

**Comment by thecoder876** [comment]
> > > > > > > > > Checklist:
> > > > > > > > > 
> > > > > > > > > * [ ]          Desktop app (in progress, see #21)
> > > > > > > > > * [ ]          Core editing system
> > > > > > > > > * [ ]          Better UI
> > > > > > > > > * [ ]          Files import and export system (.sel file extension)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Okay what the frick is a .sel file
> > > > > > > 
> > > > > > > 
> > > > > > > @AmpersandGD New extension that we'll make. SEL = SimpleEdit Level
> > > > > > 
> > > > > > 
> > > > > > But unfortunately, the .sel file extension name is taken.
> > > > > > ~snip
> > > > > 
> > > > > 
> > > > > Umm, maybe `.sl` then?
> > > 
> > > 
> > > ~snip~
> > > Come on
> > 
> > 
> > Whyeeeeee??? @AmpersandGD Then maybe `.lse`? Or `.eel`?
> 
> Those file names are both taken, but good news, the names `.gdlevel` and `.selevel` are both available!

@AmpersandGD Great, we'll go with ``.selevel``.

**Comment by AmpersandGD** [comment]
Now to encrypt it 😩

**Comment by wgyt** [comment]
> Now to encrypt it 😩

why are we encrypting?
> Those file names are both taken, but good news, the names .gdlevel and .selevel are both available!

We can use .sel even if other software uses it.

**Comment by AmpersandGD** [comment]
> > Now to encrypt it 😩
> 
> why are we encrypting?
> 
> > Those file names are both taken, but good news, the names .gdlevel and .selevel are both available!
> 
> We can use .sel even if other software uses it.


`.selevel` or `.gdlevel` makes more sense, and it's better for something unique

**Comment by AmpersandGD** [comment]
> > Now to encrypt it 😩
> 
> why are we encrypting?
> 
> > Those file names are both taken, but good news, the names .gdlevel and .selevel are both available!
> 
> We can use .sel even if other software uses it.


We encrypt it so big brain hackers upload impossible levels

**Comment by wgyt** [comment]
> `.selevel` or `.gdlevel` makes more sense, and it's better for something unique
ok
> We encrypt it so big brain hackers upload impossible levels
yeah no

**Comment by AmpersandGD** [comment]
> > `.selevel` or `.gdlevel` makes more sense, and it's better for something unique
> 
> ok
> 
> > We encrypt it so big brain hackers upload impossible levels
> 
> yeah no


Still makes more sense to encrypt level data as text to a different format

**Comment by wgyt** [comment]
> Still makes more sense to encrypt level data as text to a different format

Don't you mean convert? ***who cares if someone makes an impossible level***

**Comment by thecoder876** [comment]
> > Still makes more sense to encrypt level data as text to a different format
> 
> Don't you mean convert? _**who cares if someone makes an impossible level**_

@wgyt Yeah, I mean like it can always be deleted.
